#!/bin/bash
export PATH=$PATH:/usr/local/bin
SRV_DIR=/root/CrosswordServer/game-server/
start()
{
    cd $SRV_DIR
    nohup pomelo start -e production >/dev/null &
    exit 0;
}
stop()
{
    pomelo stop
}

case "$1" in
start)
    start
    ;;
stop)
    stop
    ;;
restart)
    stop
    start
    ;;
*)
    echo "usage: $0 start|stop|restart"
    exit 0;
esac
